server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql//localhost:3303/portfolio?serverTimezone=Asia/Seoul
    username: user
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
    secret: "+I5(i[:IyjHL^;rM+@.ut)s*6^/Y]73>zh6WeNP<%1x"